sonar.projectKey=DiegoRomero14_sistema_de_recompensas_backend
sonar.organization=diegoromero14
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/app.js,src/services/redencion.service.js,src/repositories/**