sonar.projectKey=DiegoRomero14_sistema_de_recompensas_backend
sonar.organization=diegoromero14
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=\
**/app.js,\
**/server.js,\
**/config/**,\
**/routes/**,\
**/repositories/**